apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-auth
  namespace: default
  labels:
    app: sign-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-auth
  template:
    metadata:
      labels:
        app: sign-auth
    spec:
      containers:
      - name: signauth
        image: gcr.io/famous-palisade-356103/sign-auth:$REVISION_ID
        imagePullPolicy: IfNotPresent
        env:
        - name: ENV_MONGO_CS
          value: "mongodb+srv://shaiz:12345@cluster0.ugy2c.mongodb.net/?retryWrites=true&w=majority"
        - name: ENV_MONGO_DB
          value: "test"
        - name: ENV_MONGO_COLLECTION
          value: "Data"
  #    imagePullSecrets:
   #     - name: topsecret
